Repository claranet/terraform-signalfx-detectors, pull requests merged in 2020-12, with the labels that each got.

#192 gen tf from preset configs and poc for system
  .github/workflows/main.yml
  modules/smart-agent_system-common/conf/00-heartbeat.yaml
  modules/smart-agent_system-common/conf/01-cpu.yaml
  modules/smart-agent_system-common/conf/02-load.yaml
  modules/smart-agent_system-common/conf/03-space.yaml
  modules/smart-agent_system-common/conf/04-inodes.yaml
  modules/smart-agent_system-common/conf/05-mem.yaml
  modules/smart-agent_system-common/detectors-gen.tf
  modules/smart-agent_system-common/detectors-system.tf
  modules/smart-agent_system-common/variables-gen.tf
  modules/smart-agent_system-common/variables.tf
  scripts/module/gen_detectors.sh
  scripts/templates/detector.tf.j2
  scripts/templates/values.yaml
Labels: CI, detectors, new feature

#193 Makefile
  .github/workflows/doc.yml
  .github/workflows/generator.yml
  .github/workflows/main.yml
  Makefile
  scripts/module/bootstrap.sh
  scripts/module/gen_detectors.sh
  scripts/module/gen_doc.sh
  scripts/module/gen_outputs.sh
  scripts/module/lint.sh
Labels: CI, new feature

#195 Doc renew
  CONTRIBUTING.md
  Makefile
  docs/development.md
  docs/environment.md
  docs/scripts.md
  docs/usage.md
  examples/stack/README.md
  scripts/templates/README.md
Labels: documentation, enhancement, new feature

#196 matrix old to new path and script to update configs
  docs/paths-matrix.md
Labels: documentation

#197 add spell and dead links checks to ci
  .github/workflows/doc.yml
  .gitignore
  .mlc_config.json
  .spellcheck.yaml
  .wordlist.txt
  CONTRIBUTING.md
  README.md
  docs/development.md
  docs/environment.md
  docs/paths-matrix.md
  docs/scripts.md
  docs/usage.md
  examples/stack/README.md
  modules/README.md
  scripts/templates/README.md
Labels: CI, new feature

#208 Templating: Add unit on detectors messages #207
  modules/smart-agent_system-common/conf/01-cpu.yaml
  modules/smart-agent_system-common/conf/03-space.yaml
  modules/smart-agent_system-common/conf/04-inodes.yaml
  modules/smart-agent_system-common/conf/05-mem.yaml
  modules/smart-agent_system-common/detectors-gen.tf
  modules/smart-agent_system-common/variables-gen.tf
  scripts/templates/detector.tf.j2
  scripts/templates/values.yaml
  scripts/templates/variables.tf.j2
Labels: new feature, templating

#212 #211 Generator: add rollup feature on signals
  scripts/templates/detector.tf.j2
  scripts/templates/values.yaml
Labels: new feature, templating
