Repository claranet/terraform-signalfx-detectors, pull requests merged in 2021-01, with the labels that each got.

#223 #203 bunch of makefile improvements
  .github/workflows/doc.yml
  Makefile
  docs/development.md
  docs/usage.md
  scripts/module/bootstrap.sh
  scripts/module/gen_doc.sh
  scripts/module/loop_wrapper.sh
  scripts/templates/README.md
  scripts/templates/readme.md.j2
Labels: CI, enhancement

#201 Switch detector to nagios plugin
  modules/smart-agent_nagios-status-check/README.md
  modules/smart-agent_nagios-status-check/conf/readme.yaml
  modules/smart-agent_nagios-status-check/detectors-nagios-status-check.tf
  modules/smart-agent_nagios-status-check/variables.tf
Labels: enhancement

#219 elasticache: lower free memory alerts severity
  modules/integration_aws-elasticache-common/detectors-elasticache.tf
  modules/integration_aws-elasticache-common/variables.tf
Labels: detectors, enhancement

#200 fix storage account capacity scale function definition
  modules/integration_azure-storage-account-capacity/detectors-azure-storage.tf
Labels: bug, detectors

#202 #123 [Azure] Application Gateway - capacity detector
  modules/integration_azure-application-gateway/README.md
  modules/integration_azure-application-gateway/conf/01-capacity.yaml
  modules/integration_azure-application-gateway/conf/readme.yaml
  modules/integration_azure-application-gateway/detectors-gen.tf
  modules/integration_azure-application-gateway/outputs.tf
  modules/integration_azure-application-gateway/variables-gen.tf
Labels: detectors, new feature

#231 Generator: allow to use additional filter on metric
  scripts/templates/detector.tf.j2
  scripts/templates/values.yaml
Labels: enhancement, templating

#209 Azure: Add global Storage Accounts detectors
  modules/integration_azure-storage-account/README.md
  modules/integration_azure-storage-account/common-locals.tf
  modules/integration_azure-storage-account/common-modules.tf
  modules/integration_azure-storage-account/common-variables.tf
  modules/integration_azure-storage-account/common-versions.tf
  modules/integration_azure-storage-account/conf/01-count.yaml
  modules/integration_azure-storage-account/conf/02-capacity.yaml
  modules/integration_azure-storage-account/conf/03-ingress.yaml
  modules/integration_azure-storage-account/conf/04-egress.yaml
  modules/integration_azure-storage-account/conf/05-requests-rate.yaml
  modules/integration_azure-storage-account/conf/readme.yaml
  modules/integration_azure-storage-account/detectors-gen.tf
  modules/integration_azure-storage-account/outputs.tf
  modules/integration_azure-storage-account/variables-gen.tf
Labels: detectors, new feature

#233 generator: support custom description rule
  scripts/templates/detector.tf.j2
  scripts/templates/values.yaml
Labels: new feature, templating

#230 #203 rework make targets naming
  .github/workflows/doc.yml
  .github/workflows/generator.yml
  .github/workflows/main.yml
  .wordlist.txt
  Makefile
  docs/development.md
  docs/environment.md
  docs/scripts.md
  docs/usage.md
  scripts/module/lint.sh
Labels: CI, enhancement

#235 fix global severity update
  Makefile
  scripts/module/gen_doc.sh
Labels: CI, bug, documentation

#237 improve doc for make commands
  .wordlist.txt
  Makefile
  docs/development.md
  docs/environment.md
  docs/usage.md
Labels: documentation, enhancement

#199 [Azure] API Management - detectors
  docs/severity.md
  modules/integration_azure-api-management-service/README.md
  modules/integration_azure-api-management-service/common-locals.tf
  modules/integration_azure-api-management-service/common-variables.tf
  modules/integration_azure-api-management-service/common-versions.tf
  modules/integration_azure-api-management-service/conf/readme.yaml
  modules/integration_azure-api-management-service/detectors-api_management_service.tf
  modules/integration_azure-api-management-service/modules.tf
  modules/integration_azure-api-management-service/outputs.tf
  modules/integration_azure-api-management-service/variables.tf
Labels: detectors, new feature

#204 #123 [Azure] Event Hub - capacity detector
  docs/severity.md
  modules/integration_azure-event-hub/README.md
  modules/integration_azure-event-hub/common-locals.tf
  modules/integration_azure-event-hub/common-variables.tf
  modules/integration_azure-event-hub/common-versions.tf
  modules/integration_azure-event-hub/conf/01-capacity-throttling.yaml
  modules/integration_azure-event-hub/conf/readme.yaml
  modules/integration_azure-event-hub/detectors-gen.tf
  modules/integration_azure-event-hub/modules.tf
  modules/integration_azure-event-hub/outputs.tf
  modules/integration_azure-event-hub/variables-gen.tf
Labels: detectors, new feature

#238 fix find order by using bash glob
  docs/severity.md
  modules/integration_azure-application-gateway/README.md
  modules/smart-agent_system-common/README.md
  scripts/module/gen_severity.sh
Labels: CI, bug
