Repository claranet/terraform-signalfx-detectors, pull requests merged in 2021-06, with the labels that each got.

#283 Allow overriding `filter_defaults` field
  common/module/locals.tf
  common/module/modules.tf
  common/module/variables.tf
Labels: detectors, new feature

#281 fix duplicated alert with consecutive delete
  modules/smart-agent_kubernetes-common/detectors-kubernetes-common.tf
Labels: bug, detectors

#280 upgrade signalfx provider to v6.7.3
  common/stack/versions.tf
  examples/stack/versions.tf
Labels: detectors, enhancement

#282 Add aggregation by subscription_id on GCP Pub/Sub Subscription heartbeat
  modules/integration_gcp-pubsub-subscription/variables.tf
Labels: bug, detectors

#287 add back filter-tags module for retro compatibility
  common/filter-tags/README.md
  common/filter-tags/locals.tf
  common/filter-tags/outputs.tf
  common/filter-tags/variables.tf
Labels: bug, detectors

#288 add usage examples for common use cases
  .github/workflows/doc.yml
  .wordlist.txt
  examples/stack/README.md
  examples/usage/README.md
  examples/usage/advanced.tf
  examples/usage/basic.tf
  examples/usage/filtering.tf
  examples/usage/multi-instantiation.tf
  examples/usage/notifications.tf
  examples/usage/providers.tf
  examples/usage/variables.tf
  examples/usage/versions.tf
Labels: documentation
