Repository claranet/terraform-signalfx-detectors, pull requests merged in 2022-02, with the labels that each got.

#372 source: add fame
  scripts/module/bootstrap.sh
  scripts/templates/readme.md.j2
Labels: templating, new feature

#380 use common filters for integration based modules init
  scripts/module/bootstrap.sh
Labels: bug, templating

#381 smart-agent_system-common: rename "per_cpu_enabled" variable to "agent_per_cpu_enabled"
  modules/smart-agent_system-common/README.md
  modules/smart-agent_system-common/conf/02-load.yaml
  modules/smart-agent_system-common/conf/readme.yaml
  modules/smart-agent_system-common/detectors-gen.tf
  modules/smart-agent_system-common/variables.tf
Labels: documentation, enhancement

#369 use sum stat for lambda detectors
  modules/integration_aws-lambda/README.md
  modules/integration_aws-lambda/conf/01-errors-percentage.yaml
  modules/integration_aws-lambda/conf/02-throttles.yaml
  modules/integration_aws-lambda/conf/03-invocations.yaml
  modules/integration_aws-lambda/conf/readme.yaml
  modules/integration_aws-lambda/detectors-gen.tf
  modules/integration_aws-lambda/variables-gen.tf
Labels: bug, detectors

#391 smart-agent_systemd-timers: add so warning in the readme
  modules/smart-agent_systemd-timers/README.md
  modules/smart-agent_systemd-timers/conf/readme.yaml
Labels: documentation, enhancement
